export const TEMPLATES = [
  {
    id: 'thought-leader',
    name: 'Thought Leader',
    emoji: '🧠',
    description: 'Authoritative long-form takes that position you as an expert in your field.',
    detail: 'Great for sharing industry opinions, challenging conventional wisdom, and building credibility with a professional audience.',
    preferences: {
      tone: 'Authoritative',
      style: 'Data-driven',
      audience: 'B2B',
      customInstructions: 'Open with a bold contrarian claim. Back every point with a stat or real-world example. End with a strong call to action.',
    },
    exampleGoal: 'Write a LinkedIn post on why most companies are measuring AI ROI completely wrong',
    platform: 'LinkedIn',
  },
  {
    id: 'startup-founder',
    name: 'Startup Founder',
    emoji: '🚀',
    description: 'Raw, build-in-public energy. Honest, punchy, and human.',
    detail: 'Perfect for founders sharing lessons, behind-the-scenes moments, and product updates with an authentic voice that resonates with the tech community.',
    preferences: {
      tone: 'Casual',
      style: 'Storytelling',
      audience: 'Tech Folks',
      customInstructions: 'Write in first person. Share the behind-the-scenes reality, not the highlight reel. Keep sentences short. Avoid corporate language.',
    },
    exampleGoal: 'Write a Twitter thread about what nobody tells you about launching your first product',
    platform: 'Twitter/X',
  },
  {
    id: 'educator',
    name: 'The Educator',
    emoji: '📚',
    description: 'Clear, structured explainers that make complex topics click for any reader.',
    detail: 'Ideal for breaking down technical or academic subjects into digestible content. Works especially well for blog posts and newsletters targeting learners.',
    preferences: {
      tone: 'Formal',
      style: 'Bullet-heavy',
      audience: 'Students',
      customInstructions: 'Use simple analogies to explain difficult concepts. Structure with clear headings. Define jargon immediately when used. End with a one-sentence takeaway.',
    },
    exampleGoal: 'Write a blog post explaining how large language models work, for someone with no ML background',
    platform: 'Blog',
  },
  {
    id: 'growth-marketer',
    name: 'Growth Marketer',
    emoji: '📈',
    description: 'Conversion-focused copy that hooks fast and drives action.',
    detail: 'Built for campaigns, launches, and outreach. Uses proven copywriting frameworks to move readers from curiosity to action without feeling pushy.',
    preferences: {
      tone: 'Witty',
      style: 'Conversational',
      audience: 'General Public',
      customInstructions: 'Lead with the pain point, not the product. Use the PAS framework (Problem → Agitate → Solve). Include a single, clear CTA. No filler sentences.',
    },
    exampleGoal: 'Write a product launch email for a new AI writing tool targeting small business owners',
    platform: 'Email',
  },
  {
    id: 'tech-writer',
    name: 'Tech Writer',
    emoji: '⚙️',
    description: 'Precise, developer-friendly content with depth and zero fluff.',
    detail: 'Designed for technical audiences who value accuracy and depth. Covers architecture decisions, engineering tradeoffs, and system design with rigor.',
    preferences: {
      tone: 'Formal',
      style: 'Data-driven',
      audience: 'Tech Folks',
      customInstructions: 'Use technical terms correctly but always explain them in context. Include concrete examples or analogies where relevant. Prefer active voice. Never oversimplify.',
    },
    exampleGoal: 'Write a technical blog post on the architecture tradeoffs between RAG and fine-tuning for production LLM apps',
    platform: 'Blog',
  },
];
