import Link from 'next/link';

export const metadata = { title: 'Terms of Use — TaskFlow AI' };

export default function Terms() {
  return (
    <div className="min-h-screen bg-background text-on-surface font-body">

      {/* Header */}
      <header className="w-full sticky top-0 bg-background/80 backdrop-blur-xl z-50">
        <nav className="flex items-center px-8 py-5 max-w-3xl mx-auto">
          <Link href="/" className="font-headline text-base font-semibold tracking-tight text-on-surface hover:text-primary transition-colors flex items-center gap-2">
            <span className="material-symbols-outlined text-2xl text-primary" style={{ fontVariationSettings: "'FILL' 1" }}>bolt</span>
            TaskFlow AI
          </Link>
        </nav>
      </header>

      {/* Content */}
      <main className="px-6 py-16 max-w-3xl mx-auto">
        <p className="font-label text-xs uppercase tracking-[0.3em] text-outline mb-4">Legal</p>
        <h1 className="font-headline text-3xl font-bold tracking-tight text-on-surface mb-2">Terms of Use</h1>
        <p className="font-label text-xs text-on-surface-variant mb-12">Last updated: April 2026</p>

        <div className="flex flex-col gap-10">

          <section>
            <h2 className="font-headline text-base font-semibold text-on-surface mb-3">Acceptance</h2>
            <p className="text-on-surface-variant leading-relaxed text-sm">
              By using TaskFlow AI, you agree to these terms. If you do not agree, please do not use the platform. These terms may be updated at any time; continued use constitutes acceptance of any changes.
            </p>
          </section>

          <section>
            <h2 className="font-headline text-base font-semibold text-on-surface mb-3">Permitted Use</h2>
            <p className="text-on-surface-variant leading-relaxed text-sm">
              TaskFlow AI is provided for lawful content creation purposes. You may not use it to generate spam, misinformation, harassment, or any content that violates applicable laws. You are solely responsible for the content you create and publish using this platform.
            </p>
          </section>

          <section>
            <h2 className="font-headline text-base font-semibold text-on-surface mb-3">AI-Generated Content</h2>
            <p className="text-on-surface-variant leading-relaxed text-sm">
              Outputs are generated by AI models and may contain inaccuracies. TaskFlow AI does not guarantee the factual accuracy, completeness, or fitness for purpose of any generated content. Always review and verify content before publishing.
            </p>
          </section>

          <section>
            <h2 className="font-headline text-base font-semibold text-on-surface mb-3">Intellectual Property</h2>
            <p className="text-on-surface-variant leading-relaxed text-sm">
              You retain ownership of the content goals you submit. AI-generated outputs are provided to you under the terms of the underlying model providers. TaskFlow AI claims no ownership over your generated content.
            </p>
          </section>

          <section>
            <h2 className="font-headline text-base font-semibold text-on-surface mb-3">Limitation of Liability</h2>
            <p className="text-on-surface-variant leading-relaxed text-sm">
              TaskFlow AI is provided &ldquo;as is&rdquo; without warranty of any kind. We are not liable for any direct, indirect, incidental, or consequential damages arising from your use of the platform or any content it generates.
            </p>
          </section>

          <section>
            <h2 className="font-headline text-base font-semibold text-on-surface mb-3">Contact</h2>
            <p className="text-on-surface-variant leading-relaxed text-sm">
              Questions about these terms? Visit the <Link href="/support" className="text-primary hover:underline">Support page</Link>.
            </p>
          </section>

        </div>
      </main>

      {/* Footer */}
      <footer className="px-6 py-10 max-w-3xl mx-auto flex items-center justify-between border-t border-outline-variant/20 mt-10">
        <span className="font-label text-xs text-on-surface-variant/40">© 2026 TaskFlow AI</span>
        <div className="flex gap-6 font-label text-xs text-on-surface-variant/50">
          <Link href="/privacy" className="hover:text-on-surface-variant transition-colors">Privacy</Link>
          <Link href="/support" className="hover:text-on-surface-variant transition-colors">Support</Link>
        </div>
      </footer>

    </div>
  );
}
